apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: urlservice
  name: urlservice
spec:
  containers:
    - env:
        - name: SPRING_APPLICATION_JSON
          value: '{ "mongo.connection.string"  : "mongodb+srv://admin:admin@urlmapping.bmlheqk.mongodb.net/?retryWrites=true&w=majority", "mongodb.database.name" : "URLMapping", "config.http.read.timeout" : "2", "config.http.connection.timeout" : "2", "config.node.id" : "n1", "config.range.url" : "http://host.docker.internal:8088/range/", "server.port":"9011", "server.address":"0.0.0.0", "spring.redis.host":"host.docker.internal", "spring.redis.port":"6379" }'
      image: urlservice
      name: urlservice
      ports:
        - containerPort: 9011
      resources: {}
      stdin: true
      tty: true
  restartPolicy: OnFailure
status: {}
